main: translator
translator: translator-heredoc.cpp translator-expect.cpp
	g++ -g -Wall -pedantic translator-heredoc.cpp -o translator-heredoc
	g++ -g -Wall -pedantic translator-expect.cpp -o translator-expect
clean:
	../clean.sh
